#pragma once

// Names of debugging cvars, for convenience.

// Computing inaccuracy:
#define CVARNAME_WEAPON_INACCURACY_MAXSPEED "sv_weapon_inaccuracy_maxspeed"
#define CVARNAME_WEAPON_INACCURACY_MAXFALLSPEED "sv_weapon_inaccuracy_maxfallspeed"

// Debugging inaccuracy:
#define CVARNAME_WEAPON_DEBUC_INAC_ENABLED "sv_weapon_debug_inac_enabled"
#define CVARNAME_WEAPON_DEBUG_INAC_RESTVALUE "sv_weapon_debug_inac_restvalue"
#define CVARNAME_WEAPON_DEBUG_INAC_RESTSPREAD "sv_weapon_debug_inac_restspread"
#define CVARNAME_WEAPON_DEBUG_INAC_RUNVALUE "sv_weapon_debug_inac_runvalue"
#define CVARNAME_WEAPON_DEBUG_INAC_RUNSPREAD "sv_weapon_debug_inac_runspread"
#define CVARNAME_WEAPON_DEBUG_INAC_CROUCHSHIFT "sv_weapon_debug_inac_crouchshift"
#define CVARNAME_WEAPON_DEBUG_INAC_AIRSHIFT "sv_weapon_debug_inac_airshift"
#define CVARNAME_WEAPON_DEBUG_INAC_FALLSHIFT "sv_weapon_debug_inac_fallshift"
#define CVARNAME_WEAPON_DEBUG_INAC_ATTACKCOEFF "sv_weapon_debug_inac_attackcoeff"
#define CVARNAME_WEAPON_DEBUG_INAC_DECAYCOEFF "sv_weapon_debug_inac_decaycoeff"
#define CVARNAME_WEAPON_DEBUG_INAC_FIREIMPULSE "sv_weapon_debug_inac_fireimpulse"
#define CVARNAME_WEAPON_DEBUG_INAC_FIREIMPULSECEIL "sv_weapon_debug_inac_fireimpulseceil"
#define CVARNAME_WEAPON_DEBUG_INAC_FIREIMPULSEHOLD "sv_weapon_debug_inac_fireimpulsehold"
#define CVARNAME_WEAPON_DEBUG_INAC_FIREIMPULSEDECAYWIN "sv_weapon_debug_inac_fireimpulsedecaywin"
#define CVARNAME_WEAPON_DEBUG_INAC_FIREIMPULSEDECAYMOD "sv_weapon_debug_inac_fireimpulsedecaymod"

// Inaccuracy debugging commands:
#define CVARNAME_WEAPON_DEBUG_INAC_DUMP "sv_weapon_debug_inac_dump"
#define CVARNAME_WEAPON_DEBUG_INAC_POPULATE "sv_weapon_debug_inac_populate"

// Debugging crosshair size:
#define CVARNAME_CROSSHAIR_OVR_ENABLED "cl_crosshair_ovr_enabled"
#define CVARNAME_CROSSHAIR_OVR_RAD_MIN "cl_crosshair_ovr_rad_min"
#define CVARNAME_CROSSHAIR_OVR_RAD_MAX "cl_crosshair_ovr_rad_max"
#define CVARNAME_CROSSHAIR_OVR_BAR_MIN "cl_crosshair_ovr_bar_min"
#define CVARNAME_CROSSHAIR_OVR_BAR_MAX "cl_crosshair_ovr_bar_max"

// Crosshair debugging commands:
#define CVARNAME_CROSSHAIR_OVR_POPULATE "cl_crosshair_ovr_populate"
#define CVARNAME_CROSSHAIR_OVR_DUMP "cl_crosshair_ovr_dump"

// Visualising spread and inaccuracy:
#define CVARNAME_DEBUG_WEAPON_SPREAD "cl_debug_weapon_spread"
