#pragma once

enum NPCRoninTurretBody_e
{
	NPCRONIN_BODY_ALL_LIGHTS,
	NPCRONIN_BODY_REAR_LIGHTS,
	NPCRONIN_BODY_FRONT_LIGHTS,
	NPCRONIN_BODY_NO_LIGHTS,
};

enum NPCRoninTurretSkin_e
{
	NPCRONIN_SKIN_RED_LIGHTS,
	NPCRONIN_SKIN_ORANGE_LIGHTS,
	NPCRONIN_SKIN_NO_LIGHTS,
};
