#ifndef SPECIAL_TEXTURES_HALFLIFE_H
#define SPECIAL_TEXTURES_HALFLIFE_H

#define SPECIALTEX_INTERNAL_PREFIX "*"
#define SPECIALTEX_TRANSPARENT_PREFIX "{"

#define SPECIALTEX_ENV_SKY "env_sky"

#define SPECIALTEX_LIQUID_PREFIX "!"
#define SPECIALTEX_LIQUID_SUFFIX_LAVA "lava"
#define SPECIALTEX_LIQUID_SUFFIX_SLIME "slime"
#define SPECIALTEX_LIQUID_SUFFIX_WATER "water"
#define SPECIALTEX_LIQUID_SUFFIX_LASER "laser"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_0 "cur_0"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_90 "cur_90"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_180 "cur_180"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_270 "cur_270"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_UP "cur_up"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_DOWN "cur_down"
#define SPECIALTEX_LIQUID_LAVA SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_LAVA
#define SPECIALTEX_LIQUID_SLIME SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_SLIME
#define SPECIALTEX_LIQUID_WATER SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_WATER
#define SPECIALTEX_LIQUID_LASER SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_LASER
#define SPECIALTEX_LIQUID_CURRENT_0 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_0
#define SPECIALTEX_LIQUID_CURRENT_90 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_90
#define SPECIALTEX_LIQUID_CURRENT_180 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_180
#define SPECIALTEX_LIQUID_CURRENT_270 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_270
#define SPECIALTEX_LIQUID_CURRENT_UP SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_UP
#define SPECIALTEX_LIQUID_CURRENT_DOWN SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_DOWN

#define SPECIALTEX_SKIP "skip"
#define BRUSHKEY_SKIP "SKIP"

#define SPECIALTEX_HINT "hint"
#define BRUSHKEY_HINT "HINT"

#define SPECIALTEX_NULL "null"
#define BRUSHKEY_NULL "NULL"

#define SPECIALTEX_SKY "sky"
#define BRUSHKEY_SKY "SKY"

#define SPECIALTEX_CLIP "clip"
#define BRUSHKEY_CLIP "CLIP"

#define BRUSHKEY_WATER "WATER"

#define SPECIALTEX_ORIGIN "origin"
#define BRUSHKEY_ORIGIN "ORIGIN"

#define SPECIALTEX_AAATRIGGER "aaatrigger"
#define BRUSHKEY_AAATRIGGER "AAATRIGGER"

#define SPECIALTEX_BEVEL "bevel"
#define BRUSHKEY_BEVEL "BEVEL"

#define SPECIALTEX_BOUNDINGBOX "boundingbox"
#define BRUSHKEY_BOUNDINGBOX "BOUNDINGBOX"

#define SPECIALTEX_TRANSLUCENT_PREFIX_ONLY "@"
#define SPECIALTEX_TRANSLUCENT "translucent"
#define BRUSHKEY_TRANSLUCENT "TRANSLUCENT"

#define SPECIALTEX_CUSTOMCONTENT_PREFIX "content"
#define BRUSHKEY_CUSTOMCONTENT_PREFIX "CONTENT"

#define SPECIALTEX_SOLIDHINT "solidhint"
#define BRUSHKEY_SOLIDHINT "SOLIDHINT"

#define SPECIALTEX_SPLITFACE "splitface"
#define BRUSHKEY_SPLITFACE "SPLITFACE"

#define SPECIALTEX_CUSTOMCONTENT_SOLID SPECIALTEX_CUSTOMCONTENT_PREFIX "solid"
#define SPECIALTEX_CUSTOMCONTENT_WATER SPECIALTEX_CUSTOMCONTENT_PREFIX "water"
#define SPECIALTEX_CUSTOMCONTENT_EMPTY SPECIALTEX_CUSTOMCONTENT_PREFIX "empty"
#define SPECIALTEX_CUSTOMCONTENT_SKY SPECIALTEX_CUSTOMCONTENT_PREFIX "sky"

#define BRUSHKEY_NOCLIP "NOCLIP"
#define BRUSHKEY_NULLNOCLIP "NULLNOCLIP"
#define BRUSHKEY_BEVELBRUSH "BEVELBRUSH"
#define BRUSHKEY_CLIPBEVEL "CLIPBEVEL"
#define BRUSHKEY_CLIPBEVELBRUSH "CLIPBEVELBRUSH"
#define BRUSHKEY_PREFIX_CLIPHULL "CLIPHULL"

#endif // SPECIAL_TEXTURES_HALFLIFE_H
