#ifndef SPECIAL_TEXTURES_AFTERBURNER_H
#define SPECIAL_TEXTURES_AFTERBURNER_H

/*
	Nightfire textures:
		special/bevel		-> bevel
		special/bsp			-> ?
		special/clip		-> clip
		special/enemyclip	-> NEW
		special/hint		-> hint
		special/nodraw		-> null?
		special/npcclip		-> NEW
		special/null		-> null
		special/opaque		-> ?
		special/origin		-> origin
		special/playerclip	-> NEW
		special/portal		-> ?
		special/rain		-> ?
		special/skip		-> skip
		special/sky			-> sky
		special/trigger		-> aaatrigger
		special/water		-> !water
		special/waterhack	-> ?

	The rest are left as-is but with the prefix "special/", just in case we want to create
	textures later on to use their functionality.

	I'm assuming that Worldcraft capitalises texture paths, and this is why brushkey strings exist.
	Gearcraft doesn't do this, so brushkey names are mapped to specialtex names.
*/

#define SPECIALTEX_GLOBAL_PREFIX "special/"

// These are on the texture name itself, after any path elements.
#define SPECIALTEX_INTERNAL_PREFIX "*"
#define SPECIALTEX_TRANSPARENT_PREFIX "{"

#define SPECIALTEX_ENV_SKY SPECIALTEX_GLOBAL_PREFIX "env_sky"

#define SPECIALTEX_LIQUID_PREFIX SPECIALTEX_GLOBAL_PREFIX "!"
#define SPECIALTEX_LIQUID_SUFFIX_LAVA "lava"
#define SPECIALTEX_LIQUID_SUFFIX_SLIME "slime"
#define SPECIALTEX_LIQUID_SUFFIX_WATER "water"
#define SPECIALTEX_LIQUID_SUFFIX_LASER "laser"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_0 "cur_0"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_90 "cur_90"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_180 "cur_180"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_270 "cur_270"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_UP "cur_up"
#define SPECIALTEX_LIQUID_SUFFIX_CURRENT_DOWN "cur_down"
#define SPECIALTEX_LIQUID_LAVA SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_LAVA
#define SPECIALTEX_LIQUID_SLIME SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_SLIME
#define SPECIALTEX_LIQUID_WATER SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_WATER
#define SPECIALTEX_LIQUID_LASER SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_LASER
#define SPECIALTEX_LIQUID_CURRENT_0 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_0
#define SPECIALTEX_LIQUID_CURRENT_90 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_90
#define SPECIALTEX_LIQUID_CURRENT_180 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_180
#define SPECIALTEX_LIQUID_CURRENT_270 SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_270
#define SPECIALTEX_LIQUID_CURRENT_UP SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_UP
#define SPECIALTEX_LIQUID_CURRENT_DOWN SPECIALTEX_LIQUID_PREFIX SPECIALTEX_LIQUID_SUFFIX_CURRENT_DOWN

#define SPECIALTEX_SKIP SPECIALTEX_GLOBAL_PREFIX "skip"
#define BRUSHKEY_SKIP SPECIALTEX_SKIP

#define SPECIALTEX_HINT SPECIALTEX_GLOBAL_PREFIX "hint"
#define BRUSHKEY_HINT SPECIALTEX_HINT

#define SPECIALTEX_NULL SPECIALTEX_GLOBAL_PREFIX "null"
#define BRUSHKEY_NULL SPECIALTEX_NULL

#define SPECIALTEX_NODRAW SPECIALTEX_GLOBAL_PREFIX "nodraw"
#define BRUSHKEY_NODRAW SPECIALTEX_NODRAW

#define SPECIALTEX_SKY SPECIALTEX_GLOBAL_PREFIX "sky"
#define BRUSHKEY_SKY SPECIALTEX_SKY

#define SPECIALTEX_CLIP SPECIALTEX_GLOBAL_PREFIX "clip"
#define BRUSHKEY_CLIP SPECIALTEX_CLIP

#define SPECIALTEX_PLAYERCLIP SPECIALTEX_GLOBAL_PREFIX "playerclip"
#define BRUSHKEY_PLAYERCLIP SPECIALTEX_PLAYERCLIP

#define SPECIALTEX_ENEMYCLIP SPECIALTEX_GLOBAL_PREFIX "enemyclip"
#define BRUSHKEY_ENEMYCLIP SPECIALTEX_ENEMYCLIP

#define SPECIALTEX_NPCCLIP SPECIALTEX_GLOBAL_PREFIX "npcclip"
#define BRUSHKEY_NPCCLIP SPECIALTEX_NPCCLIP

#define BRUSHKEY_WATER SPECIALTEX_LIQUID_WATER

#define SPECIALTEX_ORIGIN SPECIALTEX_GLOBAL_PREFIX "origin"
#define BRUSHKEY_ORIGIN SPECIALTEX_ORIGIN

#define SPECIALTEX_AAATRIGGER SPECIALTEX_GLOBAL_PREFIX "trigger"
#define BRUSHKEY_AAATRIGGER SPECIALTEX_AAATRIGGER

#define SPECIALTEX_BEVEL SPECIALTEX_GLOBAL_PREFIX "bevel"
#define BRUSHKEY_BEVEL SPECIALTEX_BEVEL

#define SPECIALTEX_BOUNDINGBOX "boundingbox"
#define BRUSHKEY_BOUNDINGBOX SPECIALTEX_BOUNDINGBOX

#define SPECIALTEX_TRANSLUCENT_PREFIX_ONLY "@"
#define SPECIALTEX_TRANSLUCENT "translucent"
#define BRUSHKEY_TRANSLUCENT SPECIALTEX_TRANSLUCENT

#define SPECIALTEX_SOLIDHINT "solidhint"
#define BRUSHKEY_SOLIDHINT SPECIALTEX_SOLIDHINT

#define SPECIALTEX_SPLITFACE "splitface"
#define BRUSHKEY_SPLITFACE SPECIALTEX_SPLITFACE

#define SPECIALTEX_CUSTOMCONTENT_PREFIX "content"
#define BRUSHKEY_CUSTOMCONTENT_PREFIX SPECIALTEX_CUSTOMCONTENT_PREFIX

#define SPECIALTEX_CUSTOMCONTENT_SOLID SPECIALTEX_CUSTOMCONTENT_PREFIX "solid"
#define SPECIALTEX_CUSTOMCONTENT_WATER SPECIALTEX_CUSTOMCONTENT_PREFIX "water"
#define SPECIALTEX_CUSTOMCONTENT_EMPTY SPECIALTEX_CUSTOMCONTENT_PREFIX "empty"
#define SPECIALTEX_CUSTOMCONTENT_SKY SPECIALTEX_CUSTOMCONTENT_PREFIX "sky"

// These don't seem to have corresponding texture paths. by default,
// so they're just hard-coded with the prefix.
#define BRUSHKEY_NOCLIP SPECIALTEX_GLOBAL_PREFIX "noclip"
#define BRUSHKEY_NULLNOCLIP SPECIALTEX_GLOBAL_PREFIX "nullnoclip"
#define BRUSHKEY_BEVELBRUSH SPECIALTEX_GLOBAL_PREFIX "bevelbrush"
#define BRUSHKEY_CLIPBEVEL SPECIALTEX_GLOBAL_PREFIX "clipbevel"
#define BRUSHKEY_CLIPBEVELBRUSH SPECIALTEX_GLOBAL_PREFIX "clipbevelbrush"
#define BRUSHKEY_PREFIX_CLIPHULL SPECIALTEX_GLOBAL_PREFIX "cliphull"

#endif // SPECIAL_TEXTURES_AFTERBURNER_H
