function(generate_shared_export_header exportTargetName outputFile)
	string(TOUPPER "${exportTargetName}" uppercaseTargetName)
	set(sharedLibDefLine "#define ${uppercaseTargetName}_SHARED_LIBRARY")
	configure_file("${CMAKE_SOURCE_DIR}/cmake/export_header_template.in" "${outputFile}")
endfunction()

function(generate_static_export_header exportTargetName outputFile)
	string(TOUPPER "${exportTargetName}" uppercaseTargetName)
	set(sharedLibDefLine "//#define ${uppercaseTargetName}_SHARED_LIBRARY")
	configure_file("${CMAKE_SOURCE_DIR}/cmake/export_header_template.in" "${outputFile}")
endfunction()
